version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: kestra_postgres
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: kestra
    volumes:
      - kestra_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  kestra:
    image: kestra/kestra:latest
    container_name: kestra_server
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./flows:/app/flows
      - ../data:/data
      - ~/.gcp:/root/.gcp
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: kestra
        kestra:
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
    command: server standalone
    restart: unless-stopped

volumes:
  kestra_postgres_data: